[project]
name = "digital-wallet-api"
version = "0.1.0"
description = "A digital wallet API built with FastAPI."
readme = "README.md"
requires-python = ">=3.12, <3.14"
dependencies = [
    "alembic>=1.18.5",
    "bcrypt>=5.0.0",
    "faker>=40.38.0",
    "fastapi[standard]>=0.139.2",
    "locust>=2.46.4",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.13.4",
    "pyjwt>=2.13.0",
    "pytest>=9.1.1",
    "python-jose>=3.5.0",
    "redis>=8.0.1",
    "requests>=2.34.2",
    "requests-mock>=1.12.1",
    "ruff>=0.16.7",
    "sqlalchemy>=2.0.51",
    "uuid7>=0.1.0",
]
[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pytest-cov>=7.1.0",
]
