"""is_2fa_enable and secrete_key field added

Revision ID: 8348725c723d
Revises: 9e43433b5fdb
Create Date: 2026-09-15 10:19:29.179994

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8348725c723d"
down_revision: str | Sequence[str] | None = "9e43433b5fdb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "is_2fa_enable",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "user", sa.Column("secrete_key_2fa", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "secrete_key_2fa")
    op.drop_column("user", "is_2fa_enable")
    # ### end Alembic commands ###
