"""password_lock status and login_attempt column added in User table

Revision ID: 35a549f0f5ee
Revises: 2da21c8068e3
Create Date: 2026-08-01 13:54:28.770968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a549f0f5ee'
down_revision: Union[str, Sequence[str], None] = '2da21c8068e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login_attempt', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('user', 'status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('active', 'inactive', 'password_lock', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=sa.Enum('active', 'inactive', 'password_lock', native_enum=False),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_column('user', 'login_attempt')
    # ### end Alembic commands ###
