"""profile_image column added

Revision ID: 064eed7b0dc9
Revises: 8348725c723d
Create Date: 2026-10-08 22:03:19.831428

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "064eed7b0dc9"
down_revision: str | Sequence[str] | None = "8348725c723d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("profile_image", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "profile_image")
    # ### end Alembic commands ###
