"""old_password and is_admin column added in User table

Revision ID: 2da21c8068e3
Revises: b28dd209980e
Create Date: 2026-07-31 23:13:23.100562

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2da21c8068e3"
down_revision: str | Sequence[str] | None = "b28dd209980e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("old_password", sa.String(), nullable=True))
    op.add_column(
        "user",
        sa.Column("is_admin", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_admin")
    op.drop_column("user", "old_password")
    # ### end Alembic commands ###
